name: Terraform Apply and Destroy

on:
  workflow_dispatch:
    inputs:        
      choice:
        type: choice
        required: true
        description: select terraform action
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Apply or Destroy
      run: |
        if [ "${{ github.event.inputs.action }}" == "apply" ]; then
          terraform apply  -auto-approve
        elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
          terraform destroy  -auto-approve
        else
          echo "Invalid action specified. Please choose 'apply' or 'destroy'."
          exit 1
        fi
